<?php

namespace App\Services\Modules;

use Illuminate\Http\Request;

use App\Models\Modules\Faturamento;
use App\Services\Module;

class ModuleNotasFiscaisFaturamentoService extends Module
{
	public $key				= 'faturamento';
	public $name			= 'Notas Fiscais de Faturamento (21, 22, 59)';
	public $description		= null;
	public $model			= Faturamento::class;
	public $fields			= [
		[
			'type' => 'string',
			'field' => 'id_faturamento',
			'name' => 'ID Original',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
		],
		[
			'type' => 'select',
			'field' => 'cancelada',
			'name' => 'Cancelada?',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
			'options' => [['value'=>'N', 'label'=>'Não'], ['value'=>'S', 'label'=>'Sim']],
		],
		[
			'type' => 'string',
			'field' => 'address_name',
			'name' => 'Nome Endereço',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
		],
		[
			'type' => 'date',
			'field' => 'doc_date',
			'name' => 'Data Documento',
			'tooltip' => null,
			'placeholder' => 'Data Documento',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'date',
			'field' => 'doc_due_date',
			'name' => 'Data Vencimento',
			'tooltip' => null,
			'placeholder' => 'Data Vencimento',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'date',
			'field' => 'tax_date',
			'name' => 'Data Emissão',
			'tooltip' => null,
			'placeholder' => 'Data Emissão',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
		],
		[
			'type' => 'string',
			'field' => 'card_code',
			'name' => 'Código Cliente',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
		],
		[
			'type' => 'string',
			'field' => 'sequence_code',
			'name' => 'Sequencia Numeração SAP',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'comments',
			'name' => 'Comentários',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'bpl_id_assigned_to_invoice',
			'name' => 'ID Filial ou CPNJ Faturamento',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => true,
		],
		[
			'type' => 'string',
			'field' => 'jrnl_memo',
			'name' => 'Observações Contabilidade',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'sequence_serial',
			'name' => 'Número Nota',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'series_str',
			'name' => 'Série Nota',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'sequence_model',
			'name' => 'Modelo Nota',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'chave_acesso',
			'name' => 'Chave de Acesso NFe',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'chave_verificacao',
			'name' => 'Chave Verificação NFSe',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'chave_autenticacao',
			'name' => 'Chave Autenticação Modelo 21 e 22',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'line_num',
			'name' => 'Número Linha Item',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'item_code',
			'name' => 'Código Item SAP',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'item_description',
			'name' => 'Descrição Item',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'whs_code',
			'name' => 'Código Depósito',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'usage',
			'name' => 'Utilização',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'quantity',
			'name' => 'Quantidade',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'unit_price',
			'name' => 'Valor Unitário',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'acct_code',
			'name' => 'Conta Contábil',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'id_docext',
			'name' => 'ID Fatura Sistema',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'tax_code',
			'name' => 'Código Imposto',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'f100_pis',
			'name' => 'Registro F100',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'f100_op',
			'name' => 'Operação F100',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
		[
			'type' => 'string',
			'field' => 'f100_tr',
			'name' => 'Tipo Venda F100',
			'tooltip' => null,
			'placeholder' => '',
			'description' => null,
			'columns' => 12,
			'config' => null,
			'showOnList' => false,
		],
	];
	public $layout_MenuIcons	= ['type'=>'fontawesome', 'class'=>'fa fa-calculator'];
	public $layout_ConfigIcons	= ['type'=>'fontawesome', 'class'=>'fa fa-calculator'];

	public function ValidadeRequestPost (Request $request) : array
	{
		return $request->validate([
			'cancelada'						=> 'required',
			'address_name'					=> 'required',
			'doc_date' 						=> 'required',
			'doc_due_date' 					=> '',
			'tax_date' 						=> '',
			'card_code' 					=> '',
			'sequence_code' 				=> '',
			'comments' 						=> '',
			'bpl_id_assigned_to_invoice'	=> '',
			'jrnl_memo' 					=> '',
			'sequence_serial' 				=> '',
			'series_str' 					=> '',
			'sequence_model' 				=> '',
			'chave_acesso' 					=> '',
			'chave_verificacao' 			=> '',
			'chave_autenticacao' 			=> '',
			'line_num' 						=> '',
			'item_code' 					=> '',
			'item_description' 				=> '',
			'whs_code' 						=> '',
			'usage' 						=> '',
			'quantity' 						=> '',
			'unit_price' 					=> '',
			'acct_code' 					=> '',
			'id_docext' 					=> '',
			'tax_code' 						=> '',
			'f100_pis' 						=> '',
			'f100_op' 						=> '',
			'f100_tr' 						=> '',
		]);
	}
}